name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      env:
        SERVER_SSH_KEY: ${{ secrets.SERVER_PEM }}
        SERVER_HOST: ${{ secrets.EC2_HOST }}
        SERVER_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$SERVER_SSH_KEY" > ~/.ssh/server.pem
        chmod 600 ~/.ssh/server.pem
        
    - name: Deploy to EC2
      env:
        SERVER_HOST: ${{ secrets.EC2_HOST }}
        SERVER_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        ssh -i ~/.ssh/server.pem -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST '
          cd ~/caelium &&
          git pull origin main &&
          source env/bin/activate &&
          pip install -r requirements.txt &&
          python manage.py makemigrations &&
          python manage.py migrate &&
          sudo supervisorctl restart caelium
        '